### ISSUE TITLE
Please fix icon

### ISSUE THREAD

**Issue by stoecker** [KaartGroup/highwayNameModificationJOSMPlugin#2]
Please fix the icon in build.xml. It must be "images/addresses.png". If not fixed soon I'll disable the plugin as I don't like to get permanent e-mails from our josm server backend.

**Comment by stoecker** [comment]
Disabled

**Comment by taylorsmock** [comment]
I've fixed it with https://github.com/KaartGroup/highwayNameModificationJOSMPlugin/releases/download/v0.0.3/openqa.jar, but I won't re-enable it in the JOSM plugin list for a couple of days to give you a chance to make certain it has an icon (it is showing up for me in a clean JOSM home directory when I copy the .jar file into the plugins directory, but development environments can be funny).

**Comment by stoecker** [comment]
Jar looks fine for me.

>make certain it has an icon
It is not required to have an icon, but the MANIFEST should not state a wrong entry, as this means I get spammed with e-mails and I don't like that :-)

**Comment by taylorsmock** [comment]
Fair enough. I don't like being spammed with emails either. Especially the same email every 10 minutes. In retrospect, I should have ensured that the image was working properly, but I didn't think it would be a major issue.

I'll go ahead and re-enable the plugin since the issue has been fixed.

I might file a bug report with a patch on the 00_plugin_dir_template repository splitting up the required metadata from the optional metadata and specifying that the optional metadata is optional. But I don't know if it is worth it with it also linking to the DevelopingPlugins page which specifies optional/required.
